[smpp]
host = "127.0.0.1"
port = 2775
system_id = "NfDfddEKVI0NCxO"
password = "rEZYMq5j"
system_type = ""

[message]
source_addr = "12345"
source_ton = 2
source_npi = 1
destination_addr = "491701234567"
destination_ton = 2
destination_npi = 1
body = "Hi, I am a short message."
service_type = ""

[load]
binds = 2
max_tps_per_bind = 100
inflight_per_bind = 64

